# Generated by Django 5.2 on 2025-05-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_rename_description_post_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Description',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Title',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
    ]
