# Generated by Django 5.2 on 2025-05-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Franchise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference', models.CharField()),
                ('name', models.CharField()),
                ('city', models.CharField()),
                ('link', models.URLField(blank=True, null=True)),
            ],
            options={
                'ordering': ['conference'],
            },
        ),
    ]
