# Generated by Django 5.2 on 2025-05-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('franchise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='franchise',
            name='img',
            field=models.ImageField(null=True, upload_to='franchise', verbose_name='img'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='city',
            field=models.CharField(max_length=100, verbose_name='city'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='conference',
            field=models.CharField(max_length=100, verbose_name='conference'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='link'),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
